export { default as School } from "./School";
export { default as User } from "./User";
export { default as Student } from "./Student";
export { default as Attendance } from "./Attendance";
export { default as LeaveRequest } from "./LeaveRequest";
export { default as Notification } from "./Notification";
export { default as Visitor } from "./Visitor";
export { default as Room } from "./Room";
export { default as RoomBooking } from "./RoomBooking";
export { default as Holiday } from "./Holiday";
export { default as Timetable } from "./Timetable";
export { default as QRToken } from "./QRToken";
export { default as EmergencyAlert } from "./EmergencyAlert";
export { default as Setting } from "./Setting";
export { default as Token } from "./Token";

export type { ISchool } from "./School";
export type { IUser } from "./User";
export type { IStudent } from "./Student";
export type { IAttendance } from "./Attendance";
export type { ILeaveRequest } from "./LeaveRequest";
export type { INotification } from "./Notification";
export type { IVisitor } from "./Visitor";
export type { IRoom } from "./Room";
export type { IRoomBooking } from "./RoomBooking";
export type { IHoliday } from "./Holiday";
export type { ITimetable } from "./Timetable";
export type { IQRToken } from "./QRToken";
export type { IEmergencyAlert } from "./EmergencyAlert";
export type { ISetting } from "./Setting";
export type { IToken } from "./Token";
