export { default as School } from "./School";
export { default as User } from "./User";
export { default as Student } from "./Student";
export { default as Attendance } from "./Attendance";
export { default as LeaveRequest } from "./LeaveRequest";
export { default as Notification } from "./Notification";
export { default as Visitor } from "./Visitor";
export { default as Room } from "./Room";
export { default as RoomBooking } from "./RoomBooking";
export { default as Holiday } from "./Holiday";
export { default as Timetable } from "./Timetable";
export { default as QRToken } from "./QRToken";
export { default as EmergencyAlert } from "./EmergencyAlert";
export { default as Setting } from "./Setting";
export { default as Token } from "./Token";
export { default as Department } from "./Department";
export { default as Semester } from "./Semester";
export { default as Subject } from "./Subject";
export { default as SubjectAttendance } from "./SubjectAttendance";
export { default as TeacherAttendance } from "./TeacherAttendance";
export { default as Salary } from "./Salary";
export { FeeStructure, FeePayment } from "./Fee";
export { Exam, Grade } from "./Exam";
export { default as AcademicYear } from "./AcademicYear";
export { default as Transport } from "./Transport";
export { LibraryBook, BookIssue } from "./Library";
export { Hostel, HostelAllocation } from "./Hostel";
export { default as Promotion } from "./Promotion";
export { default as FacultyWorkload } from "./FacultyWorkload";
export { default as Backup } from "./Backup";
export { default as Role } from "./Role";

export type { ISchool } from "./School";
export type { IUser } from "./User";
export type { IStudent } from "./Student";
export type { IAttendance } from "./Attendance";
export type { ILeaveRequest } from "./LeaveRequest";
export type { INotification } from "./Notification";
export type { IVisitor } from "./Visitor";
export type { IRoom } from "./Room";
export type { IRoomBooking } from "./RoomBooking";
export type { IHoliday } from "./Holiday";
export type { ITimetable } from "./Timetable";
export type { IQRToken } from "./QRToken";
export type { IEmergencyAlert } from "./EmergencyAlert";
export type { ISetting } from "./Setting";
export type { IToken } from "./Token";
export type { IDepartment } from "./Department";
export type { ISemester } from "./Semester";
export type { ISubject } from "./Subject";
export type { ISubjectAttendance } from "./SubjectAttendance";
export type { ITeacherAttendance } from "./TeacherAttendance";
export type { ISalary } from "./Salary";
export type { IFeeStructure, IFeePayment } from "./Fee";
export type { IExam, IGrade } from "./Exam";
export type { IAcademicYear } from "./AcademicYear";
export type { ITransport } from "./Transport";
export type { ILibraryBook, IBookIssue } from "./Library";
export type { IHostel, IHostelAllocation } from "./Hostel";
export type { IPromotion } from "./Promotion";
export type { IFacultyWorkload } from "./FacultyWorkload";
export type { IBackup } from "./Backup";
export type { IRole, IMenuPermission } from "./Role";
